CREATE TABLE IF NOT EXISTS public.ipo_details (
    id SERIAL PRIMARY KEY,
    company_name VARCHAR(255),
    logo_url VARCHAR(255),
    ipo_open_date DATE,
    ipo_close_date DATE,
    ipo_date VARCHAR(50),
    listing_date DATE,
    face_value VARCHAR(50),
    price_band JSONB,
    lot_size VARCHAR(50),
    offer_for_sale VARCHAR(255),
    total_issue_size JSONB,
    fresh_issue JSONB,
    issue_type VARCHAR(50),
    listing_at VARCHAR(255),
    pre_issue VARCHAR(50),
    post_issue VARCHAR(50),
    market_maker_portion VARCHAR(50),
    ipo_details_url VARCHAR(255),
    ipo_allotment_status_url VARCHAR(255),
    ipo_live_subscription_url VARCHAR(255),
    ipo_stock_price_url VARCHAR(255),
    ipo_gmp_url VARCHAR(255),
    about TEXT,
    docs_url JSONB,
    ipo_trade_information JSONB,
    ipo_listing_information JSONB,
    ipo_listing_prospectus JSONB,
    rating VARCHAR(50),
    lead_manager_data JSONB,
    ipo_gmp_data JSONB,
    ipo_registrar JSONB,
    ipo_allotment_status BOOLEAN DEFAULT FALSE,
    ipo_allotment_required_payload JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);